name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v3.5.3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        context: ./src/
        file: ./src/Dockerfile
        tags: |
          niltonpita/conversao-temperatura:${{github.run_number}}
          niltonpita/conversao-temperatura:latest
   CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.0
      - name: Configuração da credencial da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1
      
    - name: Passo 01
      run: echo "Deploy da aplicação"
