name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v3.5.3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: |
          niltonpita/kube-news:${{github.run_number}}
          niltonpita/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
    - uses: actions/checkout@v3
    - name: Passo 01
      run: echo "Deploy da aplicação"
